openshift-assisted/cluster-api-provider-openshift-assisted

bootstrap-components.yaml, bootstrap/config/manager/kustomization.yaml, bootstrap/internal/controller/agent_controller.go, bootstrap/internal/controller/agentbootstrapconfig_controller.go, bootstrap/internal/controller/agentclusterinstall_controller.go, bootstrap/internal/controller/infraenv_controller.go, controlplane-components.yaml, controlplane/api/v1beta1/agentcontrolplane_types.go, controlplane/api/v1beta1/zz_generated.deepcopy.go, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_agentcontrolplanes.yaml, controlplane/config/manager/kustomization.yaml, controlplane/config/rbac/role.yaml, controlplane/internal/controller/agentclusterinstall_controller.go, controlplane/internal/controller/agentcontrolplane_controller.go, controlplane/internal/controller/clusterdeployment_controller.go, go.mod, go.sum, metadata.yaml
=> Worker nodes

Dockerfile, bootstrap/internal/controller/agent_controller.go, bootstrap/internal/controller/agentbootstrapconfig_controller.go, bootstrap/internal/controller/agentbootstrapconfig_controller_test.go, bootstrap/internal/controller/suite_test.go, controlplane/internal/controller/agentcontrolplane_controller.go, controlplane/internal/controller/agentcontrolplane_controller_test.go, controlplane/internal/controller/clusterdeployment_controller.go, test/utils/unit.go, util/log/log.go
This PR is mainly adding tests, plus some small fixes.
=> MGMT-17972: add tests to agentbootstrapconfig controller

bootstrap/internal/controller/infraenv_controller.go, bootstrap/internal/controller/infraenv_controller_test.go
Add test coverage for infraenv controller
=> MGMT-17973: add coverage for infraenv controller

bootstrap/internal/controller/agent_controller.go, bootstrap/internal/controller/agent_controller_test.go, bootstrap/internal/controller/agentbootstrapconfig_controller_test.go, bootstrap/internal/controller/suite_test.go, test/utils/unit.go
Increase coverage for agent controller
=> MGMT-17971: increase coverage for bootstrap agent controller

bootstrap-components.yaml, bootstrap/config/rbac/role.yaml, bootstrap/internal/controller/agentbootstrapconfig_controller.go, bootstrap/main.go, controlplane-components.yaml, util/log/log.go
Missing permissions for setting the image on the template
=> bugfix: add missing rbac and tidy up published manifests

bootstrap/api/v1alpha1/agentbootstrapconfig_types.go, bootstrap/api/v1alpha1/groupversion_info.go, bootstrap/api/v1alpha1/zz_generated.deepcopy.go, bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_agentbootstrapconfigs.yaml, bootstrap/internal/controller/agent_controller.go, bootstrap/internal/controller/agentbootstrapconfig_controller.go, bootstrap/main.go
Kubeadm bootstrap just ignores any config being deleted https://github.com/kubernetes-sigs/cluster-api/blob/d1a230153b4bb27f434f6ccb3acbd630ce0979d7/bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go#L237
=> WIP: Add finalizer and deletion logic for agent bootstrapconfig

bootstrap/internal/assistedinstaller/infraenv.go, bootstrap/internal/controller/agentbootstrapconfig_controller.go, bootstrap/internal/controller/agentbootstrapconfig_controller_test.go, util/util.go
handle all supported infraenv attributes
=> handle infraenv attributes

controlplane/internal/controller/agentclusterinstall_controller.go
Cleaned up the reconcile function by splitting out several chunks of logic to separate functions, cleaning up the logging, and removing unused portions of code.
=> MGMT-17981: Refactor controlplane's agentclusterinstaller controller

bootstrap-components.yaml, bootstrap/config/manager/kustomization.yaml, bootstrap/internal/controller/agentbootstrapconfig_controller_test.go, controlplane-components.yaml, controlplane/config/manager/kustomization.yaml, controlplane/internal/controller/agentcontrolplane_controller_test.go, controlplane/internal/controller/clusterdeployment_controller.go, controlplane/internal/controller/clusterdeployment_controller_test.go, test/utils/unit.go
Add minimal test coverage for clusterdeployment controller
=> add coverage for clusterdeployment controller

controlplane/internal/imageregistry/image_registry.go, controlplane/internal/imageregistry/image_registry_test.go
Creates an ImageTagMirrorSet CR if the registries.conf specifies to pull images by tag.
=> MGMT-18188: Enable pulling images via tag

controlplane/internal/controller/agentcontrolplane_controller.go
Cleaned up logging and broke out a few functions.
=> MGMT-17982: Initial cleanup of AgentControlPlane controller

Makefile, bootstrap-components.yaml
=> Improve makefile

controlplane/internal/controller/clusterdeployment_controller.go, controlplane/internal/imageregistry/image_registry.go, controlplane/internal/imageregistry/image_registry_test.go
Limit scope of image registry file to creating the configmap for the image registry instead of accessing the kube api server.
Also moves logic of creating the image registry configmap to the cluster deployment controller and includes an update of the image registry unit tests to reflect the move.
=> MGMT-17963: Refactor image registry

controlplane/internal/controller/agentcontrolplane_controller.go, util/util.go
Cleanup controller logic for creating machine and AgentBootstrapConfig replicas.
=> MGMT-17982: Refactor AgentControlPlane replica logic

controlplane/internal/controller/clusterdeployment_controller.go, controlplane/internal/controller/clusterdeployment_controller_test.go, controlplane/internal/imageregistry/image_registry.go, controlplane/internal/imageregistry/image_registry_test.go
Includes changes from this PR https://github.com/openshift-assisted/cluster-api-agent/pull/39
=> MGMT-17983: Refactor controlplane/clusterdeployment controller

bootstrap/internal/controller/infraenv_controller.go
This filter is now unnecessary as we list by index
=> remove unnecessary agentbootstrapconfig filter

README.md
improve documentation for e2e tests usage
=> improve e2e tests documentation

README.md, test/e2e/e2e_test.go
parametrize network interface. In the future this should be automatically detected
=> e2e tests: parametrize network interface

CONTRIBUTING.md, README.md, test/ansible/run_test.yaml
Update README to include additional prerequisites for running the e2e tests and add file for contributing.
=> NO-ISSUE: Update README.md and add CONTRIBUTING.md

controlplane/api/v1alpha2/condition_consts.go, controlplane/api/v1alpha2/openshiftassistedcontrolplane_types.go, controlplane/internal/controller/agentclusterinstall_controller.go, controlplane/internal/controller/openshiftassistedcontrolplane_controller.go, controlplane/internal/controller/openshiftassistedcontrolplane_controller_test.go
add controlplane conditions to give better feedback
=> add controlplane conditions

bootstrap/api/v1alpha1/openshiftassistedconfig_types.go, bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_openshiftassistedconfigs.yaml, bootstrap/internal/controller/openshiftassistedconfig_controller.go, controlplane/api/v1alpha2/openshiftassistedcontrolplane_types.go, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_openshiftassistedcontrolplanes.yaml, controlplane/internal/controller/openshiftassistedcontrolplane_controller.go, controlplane/internal/controller/openshiftassistedcontrolplane_controller_test.go, controlplane/internal/controller/suite_test.go, go.mod, test/e2e/manifests/infrastructure-operator/kustomization.yaml, util/failuredomains/failure_domains.go, util/failuredomains/failure_domains_test.go, util/failuredomains/suite_test.go, vendor/modules.txt, vendor/sigs.k8s.io/cluster-api/util/failuredomains/failure_domains.go
Support scaling down controlplane nodes
Support failure domains
=> scale down controlplane nodes

Dockerfile.bootstrap-provider, Dockerfile.controlplane-provider, Dockerfile.j2
Resolves https://issues.redhat.com/browse/ACM-21350
=> ACM-21350: Enable CGO for FIPS compliance

assistedinstaller/infraenv.go, assistedinstaller/infraenv_test.go, bootstrap/api/v1alpha1/openshiftassistedconfig_types.go
backport of https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted/pull/247
=> MGMT-20825: add annotation to expose discovery config override
